// Code generated by "stringer -type=DeviceType -output=device_type_string.go"; DO NOT EDIT.

package devices

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Light-1]
	_ = x[Socket-2]
	_ = x[Switch-3]
	_ = x[Thermostat-4]
}

const _DeviceType_name = "LightSocketSwitchThermostat"

var _DeviceType_index = [...]uint8{0, 5, 11, 17, 27}

func (i DeviceType) String() string {
	i -= 1
	if i < 0 || i >= DeviceType(len(_DeviceType_index)-1) {
		return "DeviceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DeviceType_name[_DeviceType_index[i]:_DeviceType_index[i+1]]
}
