#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')


if [[ $STAGED_GO_FILES == "" ]]; then
  echo "No Go files to update"
else
  for file in $STAGED_GO_FILES; do
    ## Format our files
    go fmt "$file"
    
    ## Add any potential changes from our formatting to the commit
    git add "$file" 
  done
fi