// Code generated by "stringer -type=ActionType -output=action_type_string.go"; DO NOT EDIT.

package megadservice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOGGLE-1]
	_ = x[PAUSE-2]
	_ = x[REPEAT-3]
}

const _ActionType_name = "TOGGLEPAUSEREPEAT"

var _ActionType_index = [...]uint8{0, 6, 11, 17}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "SrvType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
