// Code generated by "stringer -type=ModeType -output=mode_type_string.go"; DO NOT EDIT.

package megadservice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLICK-1]
	_ = x[PRESS-2]
	_ = x[ANY-3]
}

const _ModeType_name = "CLICKPRESSANY"

var _ModeType_index = [...]uint8{0, 5, 10, 13}

func (i ModeType) String() string {
	i -= 1
	if i < 0 || i >= ModeType(len(_ModeType_index)-1) {
		return "ModeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ModeType_name[_ModeType_index[i]:_ModeType_index[i+1]]
}
