settings:
    host_ip: 192.168.88.14
    pwd: sec
    srv: 192.168.88.242
    srv_type: MQTT
    mqtt_password: kaDUN6HF

ports:
    - id: 0
      actions:
          - type: TOGGLE
            value: 31
          - type: PAUSE
            value: 1000
          - type: TOGGLE
            value: 31
            
    - id: 17
      actions:
          - type: TOGGLE
            value: 9
            
    - id: 18
      actions:
          - type: PAUSE
            value: 23
