// Code generated by "stringer -type=PortType -output=port_type_string.go"; DO NOT EDIT.

package megad2561

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IN-1]
	_ = x[OUT-2]
	_ = x[ADC-3]
	_ = x[DSen-4]
	_ = x[I2C-5]
}

const _PortType_name = "INOUTADCDSenI2C"

var _PortType_index = [...]uint8{0, 2, 5, 8, 12, 15}

func (i PortType) String() string {
	i -= 1
	if i < 0 || i >= PortType(len(_PortType_index)-1) {
		return "PortType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PortType_name[_PortType_index[i]:_PortType_index[i+1]]
}
